/** Prova libera: un solo caso operativo alla volta. */
export const PRACTICE_SCENARIOS = [
  { id: 'cash', view: 'solo', orderIds: ['demo-2'], title: 'Incasso al banco', body: 'D098 aspetta il pagamento. Incassalo e fallo entrare in DA FARE.', doText: 'CONFERMA PAGAMENTO.', dontText: 'Non preparare un ordine ancora non pagato.', success: 'payment:demo-2' },
  { id: 'lifecycle', view: 'solo', orderIds: ['demo-6'], title: 'Porta un ordine fino in fondo', body: 'Gestisci D085: INIZIA, PRONTO, poi RITIRATO.', doText: 'Segui le tre CTA nell’ordine.', dontText: 'Non saltare uno stato.', success: 'lifecycle:D085' },
  { id: 'quick-pay', view: 'solo', orderIds: ['demo-6', 'demo-2'], title: 'Non perdere il focus', body: 'Mentre lavori, usa PAGA rapido per chiudere il pagamento di un altro cliente.', doText: 'Paga D098 e torna all’ordine in focus.', dontText: 'Non cambiare schermata e non perdere l’ordine in preparazione.', success: 'quick-pay:D098' },
  { id: 'allergen', view: 'solo', orderIds: ['demo-3'], title: 'Controlla l’allergene', body: 'Apri D095 e leggi l’allergia prima di preparare.', doText: 'Controlla la nota allergene visibile nella card.', dontText: 'Non trattarla come una nota secondaria.', success: 'ack:allergen' },
  { id: 'sumup-success', view: 'payments', title: 'Esito confermato', body: 'Il pagamento SumUp è riuscito: PAGATO. L’ordine può proseguire.', doText: 'Riconosci PAGATO come incasso confermato.', dontText: 'Non avviare un reconcile o un secondo incasso.', paymentIds: ['pay-training-success'], success: 'seen:sumup-success' },
  { id: 'failed', view: 'payments', title: 'Carta rifiutata', body: 'La carta è stata rifiutata. Il pagamento non è riuscito.', doText: 'Fai riprovare il cliente con carta o altro metodo.', dontText: 'Non segnare PAGATO e non rimborsare.', paymentIds: ['pay-demo-4'], success: 'seen:failed' },
  { id: 'pending-confirmed', view: 'payments', title: 'Pending che diventa confermato', body: 'Il pagamento è ambiguo: il cliente dice di aver pagato, ma il ledger è ancora IN CORSO.', doText: 'Premi VERIFICA STATO e accetta solo l’esito confermato.', dontText: 'Non forzare PAGATO manualmente.', paymentIds: ['pay-training-confirmed'], success: 'reconcile:ord-training-confirmed' },
  { id: 'pending-still', view: 'payments', title: 'Pending ancora pending', body: 'Dopo la verifica il pagamento è ancora in elaborazione.', doText: 'Attendi e riprova più tardi.', dontText: 'Non consegnare come se fosse pagato.', paymentIds: ['pay-training-pending'], success: 'reconcile:ord-training-pending' },
  { id: 'refund-stuck', view: 'payments', title: 'Rimborso avviato, non confermato', body: 'Il rimborso è IN CORSO: non hai ancora la conferma finale.', doText: 'Controlla lo stato prima di rispondere al cliente.', dontText: 'Non avviare un secondo rimborso.', paymentIds: ['pay-training-refund-stuck-charge', 'pay-training-refund-stuck'], anomalyIds: ['ord-training-refund-stuck'], success: 'seen:refund-stuck' },
  { id: 'refund', view: 'payments', title: 'Rimborso corretto', body: 'Questo pagamento è riuscito e il cliente deve ricevere il rimborso.', doText: 'Premi RIMBORSA e conferma l’operazione simulata.', dontText: 'Non rimborsare senza una charge riuscita.', paymentIds: ['pay-demo-3'], success: 'refund:ord-4821-demo' },
  { id: 'double-refund', view: 'payments', title: 'Double refund protetto', body: 'Il rimborso è già RIMBORSATO: la stessa charge non va rimborsata di nuovo.', doText: 'Lascia l’ordine chiuso e riconosci il blocco.', dontText: 'Non cercare una seconda CTA di rimborso.', paymentIds: ['pay-training-double-charge', 'pay-training-double-refund'], success: 'seen:double-refund' },
  { id: 'unknown', view: 'payments', title: 'Esito sconosciuto', body: 'Il provider non dà una risposta determinabile.', doText: 'Verifica e segnala il caso per riconciliazione manuale.', dontText: 'Non segnare PAGATO e non ripetere azioni alla cieca.', paymentIds: ['pay-training-unknown'], success: 'reconcile:ord-training-unknown' },
  { id: 'close', view: 'payments', title: 'Chiusura turno', body: 'Hai visto tutti i casi. Chiudi la simulazione solo dopo aver riconosciuto ogni esito.', success: 'close' },
];

export const PRACTICE_COPY = {
  title: 'PROVA LIBERA — SIMULAZIONE TURNO',
  body: 'Un solo problema alla volta. Le schermate sono quelle vere, ma ordini e pagamenti sono fixture locali.',
};
